name: flutter_task_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4

  flutter:
    sdk: flutter
  url_launcher: ^6.1.12
  flutter_slidable: ^3.0.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true
  
  
